site_name: PS Private Gallery Walkthrough
site_author: Mike Lombardi
theme: psinder
site_description: "A walkthrough of deploying and configuring a PowerShell Private Gallery to Azure via ARM Templates, DSC Configurations, and Visual Studio Team Services Build."
repo_url: "https://github.com/michaeltlombardi/PSPrivateGalleryWalkthrough"
copyright: "The PSPrivateGalleryWalkthrough project is licensed under the <a href='https://github.com/michaeltlombardi/PSPrivateGalleryWalkthrough/blob/master/LICENSE.md'>MIT license</a>"

pages:
    - About: index.md
    - Getting Started:
        - Before We Begin: Getting-Started\Before-We-Begin.md
    - Step-By-Step:
        - 1. Adding Your Fork to VSTS:                       Step-By-Step\1-Adding-Your-Fork-to-VSTS.md
        - 2. Adding Azure to VSTS:                           Step-By-Step\2-Adding-Azure-to-VSTS.md
        - 3. Defining Your VSTS-Build:                       Step-By-Step\3-Defining-Your-VSTS-Build.md
        - 4. Deploying and Registering Your Private Gallery: Step-By-Step\4-Deploying-And-Registering-Your-Private-Gallery.md
        - 5. Publishing To Your Private Gallery:             Step-By-Step\5-Publishing-To-Your-Private-Gallery.md
    - Concepts:
        - Build Variables:    Concepts\Build-Variables.md
        - The Configurations: Concepts\The-PowerShell-Private-Gallery-Configurations.md

extra:
    version: 0.1.2